version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=schedule_db
      - LISTEN_ADDRESSES=*
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgres:/var/lib/postgres
